### ISSUE TITLE
On Frozen Binaries, using "Save" crashes the game

### ISSUE THREAD

**Issue by Penaz91** [Penaz91/Glitch_Heaven#12]
[2015-12-12 23:26:44,977](Glitch_Heaven.Bootstrapper) - CRITICAL --- There has been an exception, printing traceback
Traceback (most recent call last):
  File "<string>", line 72, in <module>
  File "c:\Users\Penaz\Desktop\PyInstaller-3.0\PyInstaller-3.0\Glitch_Heaven\Game\mainmenu.py", line 173, in main
  File "c:\Users\Penaz\Desktop\PyInstaller-3.0\PyInstaller-3.0\Glitch_Heaven\Game\mainmenu.py", line 79, in <lambda>
  File "c:\Users\Penaz\Desktop\PyInstaller-3.0\PyInstaller-3.0\Glitch_Heaven\Game\game.py", line 429, in main
  File "c:\Users\Penaz\Desktop\PyInstaller-3.0\PyInstaller-3.0\Glitch_Heaven\Game\game.py", line 287, in saveGame
  File "c:\Users\Penaz\AppData\Local\Programs\Python\Python35-32\lib\shelve.py", line 243, in open
  File "c:\Users\Penaz\AppData\Local\Programs\Python\Python35-32\lib\shelve.py", line 227, in **init**
  File "c:\Users\Penaz\AppData\Local\Programs\Python\Python35-32\lib\dbm__init__.py", line 75, in open
ImportError: no dbm clone found; tried ['dbm.gnu', 'dbm.ndbm', 'dbm.dumb']

Seems that Frozen Binaries don't include DBM clones.
Possible fix:
    try:
        import dbhash
        import gdbm
        import dbm
        import dumbdbm
    except ImportError:
        logger.info("Couldn't load some modules, skipping..."

This should allow pyinstaller to get the libs

**Comment by Penaz91** [comment]
Fixed by making a new Hook to dbm for PyInstaller, see Issue #1733 at PyInstaller Repo.
