### ISSUE TITLE
New Particle System Causes Crashes

### ISSUE THREAD

**Issue by Penaz91** [Penaz91/Glitch_Heaven#3]
The new particle system causes crashes on death with the following traceback:

`Traceback (most recent call last):
  File "run.py", line 41, in <module>
    menu().main(screen, keys, config)
  File "/home/penaz/Varie/Progetti/Roba In Python/GH/Glitch_Heaven/Game/mainmenu.py", line 106, in main
    self.items[self.currentItem].function()
  File "/home/penaz/Varie/Progetti/Roba In Python/GH/Glitch_Heaven/Game/mainmenu.py", line 56, in <lambda>
    "newgame"))
  File "/home/penaz/Varie/Progetti/Roba In Python/GH/Glitch_Heaven/Game/game.py", line 355, in main
    self.tilemap.draw(screen)
  File "/home/penaz/Varie/Progetti/Roba In Python/GH/Glitch_Heaven/Game/libs/tmx.py", line 683, in draw
    layer.draw(screen)
  File "/home/penaz/Varie/Progetti/Roba In Python/GH/Glitch_Heaven/Game/libs/tmx.py", line 616, in draw
    ox, oy = self.position
AttributeError: 'SpriteLayer' object has no attribute 'position'
`

**Comment by Penaz91** [comment]
Issue was caused by a memory leak in the particle system. Should be now solved
